"""Render the NDJSON telemetry log into the committed markdown report.

Same regen-and-commit pattern as the previews: the report is derived from the
log, never hand-edited, and regenerating it from an unchanged log reproduces
it byte for byte (everything here is a pure function of the records).

A malformed log line raises rather than being skipped: the log is committed,
so a line that will not parse is corruption to fix at the source, and a
report that silently ignored it would claim a history it did not read.
"""

from __future__ import annotations

import json

# The report keeps the full run history readable by bounding the run table;
# the per-part and budget sections always come from the latest run carrying
# that data, so they never grow with history at all.
MAX_RUN_ROWS = 30

# Budget rows worth a reader's attention: below this headroom a preview is one
# regeneration away from failing readme-gate's budget check.
LOW_HEADROOM_PCT = 15.0


def parse_log(text: str) -> list[dict]:
    """Parse NDJSON into records, oldest first. Raises ValueError naming the
    offending line number on malformed JSON or a record without the fields
    every schema-1 record carries."""
    records = []
    for n, line in enumerate(text.splitlines(), start=1):
        if not line.strip():
            continue
        try:
            rec = json.loads(line)
        except json.JSONDecodeError as e:
            raise ValueError(f"telemetry log line {n} is not valid JSON: {e}") from e
        if not isinstance(rec, dict) or "schema" not in rec or "kind" not in rec:
            raise ValueError(
                f"telemetry log line {n} is not a telemetry record "
                f"(every record carries 'schema' and 'kind')"
            )
        records.append(rec)
    return records


def _esc(text: str) -> str:
    # Same reason gate-summary.py escapes: a stray pipe silently shifts every
    # cell after it.
    return str(text).replace("|", "\\|")


def _meta(rec: dict, key: str) -> str:
    return str(rec.get("meta", {}).get(key, "—"))


def render(records: list[dict]) -> str:
    """The whole report, as one markdown string ending in a newline."""
    out: list[str] = []
    out.append("# Telemetry report")
    out.append("")
    out.append(
        "<!-- GENERATED by ./scripts/telemetry.sh report from telemetry/log.ndjson"
        " — do not edit by hand -->"
    )
    out.append("")
    gate_runs = [r for r in records if r.get("kind") == "gate-run"]
    if not gate_runs:
        out.append("_No gate runs recorded yet. CI appends one record per")
        out.append("full-catalog gate run on the default branch; see")
        out.append("`tools/telemetry/README.md`._")
        out.append("")
        return "\n".join(out)

    out.append("## Gate runs")
    out.append("")
    shown = gate_runs[-MAX_RUN_ROWS:]
    if len(gate_runs) > len(shown):
        out.append(
            f"_Latest {len(shown)} of {len(gate_runs)} recorded runs "
            f"(the full history is in `telemetry/log.ndjson`)._"
        )
        out.append("")
    out.append("| When (UTC) | Event | Scope | Parts gated | Result | Gate wall time |")
    out.append("|---|---|---|---|---|---|")
    for rec in reversed(shown):
        gate = rec.get("gate", {})
        parts = gate.get("parts", [])
        seconds = sum(gate.get("design_seconds", {}).values())
        result = "✅ pass" if gate.get("ok") else f"❌ {gate.get('fail_lines', '?')} FAIL line(s)"
        skips = len(gate.get("archived_skips", []))
        scope = _meta(rec, "designs")
        if skips:
            scope += f" ({skips} archived skipped)"
        out.append(
            f"| {_esc(rec.get('utc', '—'))} | {_esc(_meta(rec, 'event'))} "
            f"| {_esc(scope)} | {len(parts)} | {result} "
            f"| {seconds}s |"
        )
    out.append("")

    latest_with_parts = next((r for r in reversed(gate_runs) if r.get("gate", {}).get("parts")), None)
    if latest_with_parts is not None:
        gate = latest_with_parts["gate"]
        out.append("## Latest gated parts")
        out.append("")
        out.append(f"_From the run recorded {_esc(latest_with_parts.get('utc', '—'))}._")
        out.append("")
        out.append("| Part | Score | Findings | Est. print time | Filament (g, PLA est.) |")
        out.append("|---|---|---|---|---|")
        for p in gate["parts"]:
            findings = []
            if p.get("criticals"):
                findings.append(f"{p['criticals']} critical")
            if p.get("warnings"):
                findings.append(f"{p['warnings']} warning" + ("s" if p["warnings"] > 1 else ""))
            if p.get("slice_failed"):
                findings.append("slice failed")
            score = p.get("score")
            score_cell = f"{score}/100" if score is not None else "no report ❌"
            out.append(
                f"| `{_esc(p['stl'])}` | {score_cell} | {_esc(', '.join(findings)) or '—'} "
                f"| {_esc(p.get('print_time') or '—')} | {_esc(p.get('filament_g') or '—')} |"
            )
        out.append("")
        times = gate.get("design_seconds", {})
        if times:
            out.append("### Gate wall time per design")
            out.append("")
            out.append("| Design | Render+gate |")
            out.append("|---|---|")
            for name, secs in sorted(times.items(), key=lambda kv: (-kv[1], kv[0])):
                out.append(f"| `{_esc(name)}` | {secs}s |")
            out.append("")

    latest_with_budgets = next((r for r in reversed(gate_runs) if r.get("budgets")), None)
    if latest_with_budgets is not None:
        out.append("## Preview budget headroom")
        out.append("")
        out.append(
            f"_Committed preview bytes vs. the shared budgets in "
            f"`scripts/preview-budget.sh`, from the run recorded "
            f"{_esc(latest_with_budgets.get('utc', '—'))}; nearest its cap first._"
        )
        out.append("")
        out.append("| Preview | Bytes | Budget | Headroom |")
        out.append("|---|---|---|---|")
        for b in latest_with_budgets["budgets"]:
            flag = " ⚠️" if b["headroom_pct"] < LOW_HEADROOM_PCT else ""
            out.append(
                f"| `{_esc(b['file'])}` | {b['bytes']:,} | {b['budget']:,} "
                f"| {b['headroom_pct']}%{flag} |"
            )
        out.append("")

    return "\n".join(out)
