#!/usr/bin/env bash
# Regenerate the design gallery section of the top-level README.md.
#   ./scripts/gallery.sh          # rewrite README.md between the markers
#   ./scripts/gallery.sh --check  # exit 1 if the committed gallery is stale
#
# One row per design directory: contact-sheet thumbnail (from
# designs/<name>/previews/contact-sheet.png, rendered fresh if missing),
# a one-liner scraped from NOTES.md's "## Goal" section (falling back to
# the README product page's intro pitch), and a link to the design dir.
# Only the region between the markers is touched — hand-written prose
# around it survives regeneration. Run after adding or renaming a design;
# check.sh fails if the committed gallery drifts from the design list.
set -euo pipefail

cd "$(dirname "$0")/.."

BEGIN='<!-- gallery:begin (generated by scripts/gallery.sh — edit prose outside the markers) -->'
END='<!-- gallery:end -->'

CHECK=0
[[ "${1:-}" == "--check" ]] && CHECK=1

# one-liner for a design: NOTES.md "## Goal" paragraph, else README intro
pitch() {
  local name="$1" line
  line="$(awk '/^##[[:space:]]+Goal/ { hit=1; next }
               hit && /^[[:space:]]*$/ { if (got) exit; next }
               hit && /^#/ { exit }
               hit { printf "%s ", $0; got=1 }' \
          "designs/${name}/NOTES.md" 2>/dev/null || true)"
  if [[ -z "$line" ]]; then
    line="$(awk 'NR==1 && /^#/ { next }
                 /^[[:space:]]*$/ { next }
                 /^[#!\[|<]/ { next }
                 { print; exit }' "designs/${name}/README.md" 2>/dev/null || true)"
  fi
  line="$(echo "$line" | sed 's/[[:space:]]*$//')"
  # a Goal paragraph that leads into a list ends with "...:" — drop the
  # dangling fragment and keep the complete sentences before it
  if [[ "$line" == *: && "$line" == *.* ]]; then
    line="${line%.*}."
  fi
  printf '%s' "$line"
}

gallery() {
  echo "$BEGIN"
  echo "| Design | |"
  echo "|---|---|"
  local dir name
  for dir in designs/*/; do
    name="$(basename "$dir")"
    [[ -f "designs/${name}/${name}.scad" ]] || continue
    local thumb="designs/${name}/previews/contact-sheet.png"
    if [[ ! -f "$thumb" ]]; then
      if [[ "$CHECK" == 1 ]]; then
        echo "gallery --check: ${thumb} missing — run ./scripts/gallery.sh" >&2
        exit 1
      fi
      echo "gallery: rendering missing ${thumb}" >&2
      ./scripts/render.sh "$name" >&2
      mkdir -p "designs/${name}/previews"
      cp "build/${name}.png" "$thumb"
    fi
    printf '| <a href="designs/%s/"><img src="%s" width="320" alt="%s previews"></a> | **[%s](designs/%s/)** — %s |\n' \
      "$name" "$thumb" "$name" "$name" "$name" "$(pitch "$name")"
  done
  echo "$END"
}

if ! grep -qF "$BEGIN" README.md || ! grep -qF "$END" README.md; then
  echo "error: README.md is missing the gallery markers" >&2
  exit 1
fi

new="$(gallery)"
# splice: everything before BEGIN, the fresh gallery, everything after END
out="$(awk -v begin="$BEGIN" -v end="$END" -v repl="$new" '
  index($0, begin) { print repl; skip=1; next }
  index($0, end)   { skip=0; next }
  !skip { print }' README.md)"

if [[ "$CHECK" == 1 ]]; then
  if [[ "$out" != "$(cat README.md)" ]]; then
    echo "gallery --check: README.md gallery is stale — run ./scripts/gallery.sh" >&2
    exit 1
  fi
  echo "gallery: up to date"
else
  printf '%s\n' "$out" > README.md
  echo "gallery: README.md updated"
fi
